### ISSUE TITLE
Switching team without changing class allows you to place other team's block colors

### ISSUE THREAD

**Issue by Kleadron** [Kleadron/infiniminer#1]
![image](https://user-images.githubusercontent.com/39423518/117556288-07b7f000-b01c-11eb-9a89-ba35e1ae4f2a.png)
Minimap shows I am on the blue team, but my build gun has red blocks.

**Comment by Kleadron** [comment]
You must also change your class entirely for changes to take effect. Switching the same class does not fix it.

**Comment by LeonetKenner** [comment]
i think that was because it was in sandbox mode.
